name: Build

on: [push]

jobs:
  build-windows-dynamic:
    name: Win64
    runs-on: windows-latest
    strategy:
      matrix:
        buildtype: ["Debug", "Release"]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: choco install -y ninja re2c
      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.204.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Update vcpkg
        run: |
          git -C $env:VCPKG_INSTALLATION_ROOT pull
      - name: Configure
        env:
          CC: clang-cl
          CXX: clang-cl
        run: |
          cmake `
            --toolchain $env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake `
            -S ${{ github.workspace }} `
            -B build `
            -G Ninja `
            -DVCPKG_TARGET_TRIPLET=x64-windows-dynamic-sciter `
            -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }}
      - name: Build
        run: cmake --build build
      - name: Package
        working-directory: build
        run: |
          cpack -G ZIP
      - uses: actions/upload-artifact@v3
        with:
          name: ogler-${{ matrix.buildtype }}-dyn
          path: build/*.zip
